apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: cloud-deploy-kus
description: main application pipeline
serialPipeline:
 stages:
 - targetId: devtarget
   profiles: 
   - dev
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: devtarget
description: development namespace
gke:
 cluster: projects/My First Project/locations/us-central1-c/clusters/ci-cd
